#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V

bspc config border_width         1
bspc config window_gap           0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config pointer_follows_focus true
bspc config focus_follows_pointer true

bspc rule -a Gimp desktop='^3' follow=on
bspc rule -a Shotcut desktop='^5' follow=on focus=on
bspc rule -a Firefox desktop='^2' follow=on focus=on
bspc rule -a mplayer2 state=floating
bspc rule -a Yad state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a ffplay state=floating focus=on
bspc rule -a Pcmanfm state=floating focus=on
bspc rule -a mpv state=floating focus=on


# Border
bspc config focused_border_color        "#cd0f0f"
bspc config normal_border_color         "#073642"
bspc config active_border_color         "#073642"

#########

feh --bg-scale ~/Pictures/Wallpaper-1.jpg &
xsetroot -cursor_name left_ptr &
~/.config/bspwm/scripts/low_bat_notifier.sh &


